# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ www, blog ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'www'
          path: www
          submodules: true
          
      - uses: actions/checkout@v2
        with:
          ref: 'blog'
          submodules: true
          path: blog

      - name: Install python deps
        run: |
          pip3 install setuptools
          cd blog
          pip3 install -r requirements.txt

      - name: Pull blog content
        env:
          GD_SERVICE_ACC_INFO: ${{ secrets.GD_SERVICE_ACC_INFO }}
          GD_FOLDER_ID: ${{ secrets.GD_FOLDER_ID }}
        run: |
          cd $GITHUB_WORKSPACE/blog/content/post
          find . -type f -not -name '_index.md' -delete
          rm -fr $GITHUB_WORKSPACE/blog/static/j-resources
          $GITHUB_WORKSPACE/blog/joplin_to_hugo.py /tmp/posts $GITHUB_WORKSPACE/blog/content/post
          mv /tmp/posts/.resource $GITHUB_WORKSPACE/blog/static/j-resources

          
      - name: Checkout master to /public
        run: |
          cd www
          rm -fr public
          git fetch --no-tags --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git worktree add -B master public origin/master
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
      
      - name: Build www
        run:
          cd www && hugo
      
      - name: Build blog
        run:
          cd blog && hugo -d $GITHUB_WORKSPACE/www/public/blog
      
      - name: Preparing publishing
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          cd $GITHUB_WORKSPACE/www/public && git add --all && git commit -m "Publishing to master"
          
      - name: action-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          directory: www/public
